sudo: false
language: node_js
notifications:
  email: false
node_js:
  - '8' 
jobs:
  include:
    - stage: "Test"
      before_script:
        - chmod +x build_typescript-with-example.sh
        - chmod +x build_typescript-with-redux.sh
        - chmod +x build_typescript.sh
      script:
        - ./build_typescript-with-example.sh
        - ./build_typescript-with-redux.sh
        - ./build_typescript.sh
      after_success:
        - npm run semantic-release
branches:
  only:
    - master
    - /^greenkeeper/.*$/
