sudo: false
language: node_js
notifications:
  email: false
node_js:
  - '8'
before_script: chmod +x build.sh
script: ./build.sh
after_success:
  - npm run semantic-release
branches:
  only:
    - master
    - /^greenkeeper/.*$/
