sudo: false
language: node_js
notifications:
  email: false
node_js:
  - '8'
before_install: cd typescript-with-redux
before_script:
  - npm prune
install: npm install
script:
  - npm run test
branches:
  only:
    - master
