sudo: false
language: node_js
notifications:
  email: false
node_js:
  - '8'
cache:
  directories:
    - "$HOME/.npm"
before_install:
  - cd ./typescript-with-redux
  - npm install
  - npm run test
branches:
  only:
    - master
